<?php 

	// connect to database
	$db = mysqli_connect('localhost', 'root', '', 'mywebsite');?>
<!DOCTYPE html>
<html>
<head>
<title>SKEIN CARE</title>
    <link rel="stylesheet" type="text/css" href="style1.css">
</head>
   <body style="background: #128184 ">
       <div class="headerhome">
		<h2>SKIN CARE</h2>
	</div>

   <form method="post" class="stylehome" action="home.php">
  
<b><h1> This section we work in hem wriht nowe hare you can
    <a href="home.php" class="mx-2" role="button"></b>
    
  <b>BACK</b></h1>
</div></a>
   </form>
</body>
</html>