<?php 

	// connect to database
	$db = mysqli_connect('localhost', 'root', '', 'mywebsite');?>
<!DOCTYPE html>
<html>
<head>
<title>KERAM</title>
    <link rel="stylesheet" type="text/css" href="style1.css">
</head>
   <body style="background: #128184 ">
       <div class="headerhome">
		<h2>KERAMS</h2>
	</div>

   <form method="post" class="stylehome" action="home.php">
   	
 <img src="c1.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
 <nav class="nnavbar-toggler-icon">
<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Google Fonts -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.0/css/mdb.min.css" rel="stylesheet">
  <img src="c2.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
   <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$900SD</button>
  </form>
</nav>
   
   <img src="c3.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
      <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$500SD</button>
  </form>
</nav>


    <img src="c4.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
   <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$600SD</button>
  </form>
</nav>
     <img src="c5.jpeg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
        <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$950SD</button>
  </form>
</nav>
      <img src="c6.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
         <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$660SD</button>
  </form>
</nav>

       <img src="c7.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>

   <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$670SD</button>
  </form>
</nav>
        <img src="c8.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
           <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$1300SD</button>
  </form>
</nav>

         <img src="c0.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
            <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$SD</button>
  </form>
</nav>
   </form>
</body>
</html>