<?php 

	// connect to database
	$db = mysqli_connect('localhost', 'root', '', 'mywebsite');?>
<!DOCTYPE html>
<html>
<head>
<title>GLRSLIN_PAGE</title>
    <link rel="stylesheet" type="text/css" href="style1.css">
</head>
   <body style="background: #128184 ">
       <div class="headerhome">
		<h2>GLRSLIN</h2>
	</div>

   <form method="post" class="stylehome" action="home.php">

  <img src="1.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
      <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$500SD</button>
  </form>
</nav>

    <img src="2.jpeg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
      <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$500SD</button>
  </form>
</nav>

      <img src="3.png"></img>
      <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$500SD</button>
  </form>
</nav>


        <img src="4.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></i>

      <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$500SD</button>
  </form>
</nav>
          <img src="5.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>

        <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$500SD</button>
  </form>
</nav>
            <img src="6.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>

      <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$500SD</button>
  </form>
</nav>

              <img src="7.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>

      <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$500SD</button>
  </form>
</nav>
                <img src="8.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>

      <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$500SD</button>
  </form>
</nav>
                  <img src="9.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
      <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$500SD</button>
  </form>
</nav>
   </form>
</body>
</html>