<?php 

	// connect to database
	$db = mysqli_connect('localhost', 'root', '', 'mywebsite');?>
<!DOCTYPE html>
<html>
<head>
<title> MEKUBE</title>
    <link rel="stylesheet" type="text/css" href="style1.css">
</head>
   <body style="background: #128184 ">
       <div class="headerhome">
		<h2>MEKAUB</h2>
	</div>

   <form method="post" class="stylehome" action="home.php">
   	 <img src="m1.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
	 <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
    <button class="btn btn-outline-success" type="button"><a href="file:///C:/Users/soso/Desktop/bs4/New%20folder/login.html?">soule</button>
    </a>
    <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
  </form>
</nav>

	 <img src="m2.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
<nav class="nnavbar-toggler-icon">
  <form class="form-inline">
    <button class="btn btn-outline-success" type="button"><a href="file:///C:/Users/soso/Desktop/bs4/New%20folder/login.html?">soule</button>
    </a>
    <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
  </form>
</nav>

	 <img src="m3.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
	 <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
    <button class="btn btn-outline-success" type="button"><a href="file:///C:/Users/soso/Desktop/bs4/New%20folder/login.html?">soule</button>
    </a>
    <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
  </form>
</nav>


	 <img src="m4.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
	 <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
    <button class="btn btn-outline-success" type="button"><a href="file:///C:/Users/soso/Desktop/bs4/New%20folder/login.html?">soule</button>
    </a>
    <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
  </form>
</nav>


	 <img src="m5.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
	 <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
    <button class="btn btn-outline-success" type="button"><a href="file:///C:/Users/soso/Desktop/bs4/New%20folder/login.html?">soule</button>
    </a>
    <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
  </form>
</nav>


	 <img src="m6.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
<nav class="nnavbar-toggler-icon">
  <form class="form-inline">
    <button class="btn btn-outline-success" type="button"><a href="file:///C:/Users/soso/Desktop/bs4/New%20folder/login.html?">soule</button>
    </a>
    <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
  </form>
</nav>

	 <img src="m7.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
<nav class="nnavbar-toggler-icon">
  <form class="form-inline">
    <button class="btn btn-outline-success" type="button"><a href="file:///C:/Users/soso/Desktop/bs4/New%20folder/login.html?">soule</button>
    </a>
    <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
  </form>
</nav>
	 <img src="m8.jpg" width="200" height="200" class="img-thumbnali mx-auto d-block" alt="" loading="lazy"></img>
	 <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
    <button class="btn btn-outline-success" type="button"><a href="file:///C:/Users/soso/Desktop/bs4/New%20folder/login.html?">soule</button>
    </a>
    <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
  </form>
</nav>
   </form>
</body>
</html>