<?php include('server.php') ?>
<!DOCTYPE html>
<html>
<head>
	<title>Login Form</title>
	 <link rel="stylesheet" type="text/css" href="style1.css">
</head>
<body style="background: #128184 ">
	<div class="header">
		<h2>TO FIND US</h2>
	</div>

    <form method="post" action="home.php">

	<nav>  <form class="form-inline"></nav>
<main><!-- Jumbotron -->
<div class="jumbotron text-center">

  <!-- Title -->
  <h4 class="card-title h4 pb-2"><strong>WE WILE BE HABE TO VISET US IN OUR BLEIS </strong></h4>

  <!-- Card image -->
  <div class="view overlay my-4">
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3843.75233760144!2d32.592659685629314!3d15.551401889202664!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x168e90fb9bbfade3%3A0x82bcc3f2b8aa7c4e!2semirates%20collage%20since%20and%20tecnology!5e0!3m2!1sar!2s!4v1606316294233!5m2!1sar!2s" style="max-width: 600px; width: 100%; height: 400px" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    <a href="#">
      <div class="mask rgba-white-slight"></div>
    </a>
  </div>

  <h5 class="indigo-text h5 mb-4">OUER PHONE</h5>

  <p class="card-text">
    CALL ONE OF THIS 
    <br>
    0920995343
      <br>
      0929080129
      <br>
      0920550596
      <br>
0907571379
    </p>

  <!-- Linkedin -->
  <a class="fa-lg p-2 m-2 li-ic"><i class="fab fa-linkedin-in grey-text"></i></a>
  <!-- Twitter -->
  <a class="fa-lg p-2 m-2 tw-ic"><i class="fab fa-twitter grey-text"></i></a>
  <!-- Dribbble -->
  <a class="fa-lg p-2 m-2 fb-ic"><i class="fab fa-facebook-f grey-text"></i></a>

</div>
<!-- Jumbotron --></main>

    </form>
</body>
</html>