<?php 

	// connect to database
	$db = mysqli_connect('localhost', 'root', '', 'mywebsite');?>
<!DOCTYPE html>
<html>
<head>
<title>LOTION</title>
    <link rel="stylesheet" type="text/css" href="style1.css">
</head>
   <body style="background: #128184 ">
       <div class="headerhome">
		<h2>LOTIONS</h2>
	</div>

   <form method="post" class="stylehome" action="home.php">
   	
 <img src="l1.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
   <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$900SD</button>
  </form>
</nav>

  <img src="l2.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
        <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$500SD</button>
  </form>
</nav>

   <img src="l3.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
 <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
    <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$880SD</button>
  </form>
</nav>

    <img src="l4.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
 <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
    <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$880SD</button>
  </form>
</nav>

     <img src="l5.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
   <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$600SD</button>
  </form>
</nav>
      <img src="l6.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
       <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
    <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$880SD</button>
  </form>
</nav>

       <img src="l7.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
                <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$660SD</button>
  </form>
</nav>


        <img src="l8.jpg" width="200" height="200" class="d-inline-block align-top" alt="" loading="lazy"></img>
                <nav class="nnavbar-toggler-icon">
  <form class="form-inline">
  <button class="btn btn-sm btn-outline-secondary" type="button">the brais</button>
    <button class="btn btn-outline-success" type="button">$950SD</button>
  </form>
</nav>
   </form>
</body>
</html>