<?php 

	// connect to database
	$db = mysqli_connect('localhost', 'root', '', 'mywebsite');?>
<!DOCTYPE html>
<html>
<head>
<title>CONECTED TO AS</title>
    <link rel="stylesheet" type="text/css" href="style1.css">
</head>
   <body style="background: #128184 ">
       <div class="headerhome">
		<h2>CALL TO US</h2>
	</div>

   <form method="post" class="stylehome" action="home.php">
   	
   </form>
</body>
</html>